In [2]:
import torch

In order to work with functions that take in tensors as input and calculate **gradient** for optimization, we must use the *requires_grad* parameter and set to true.

In [ ]:
t_X = torch.ones(3, requires_grad=True) # define a tensor and set requires_grad as true so it knows to calculate gradient
t_X

tensor([1., 1., 1.], requires_grad=True)

Gradient is calculated through a process called **Backpropagation**

Using our earlier example, the process is as follows:
- ***Forward Pass*** $\rightarrow$ use inputs to calculate output ($t_Y$ in this case)
- ***Function for Backpropagation*** $\rightarrow$ Pytorch creates and stores a function used for the backpropagation, this will *point to a gradient function* (`grad_fn`)
- ***Backward Path*** $\rightarrow$ Calculates gradient of $t_Y$ with respect to $t_X$ here

In [12]:
# function test example
t_Y = t_X * 2
t_Y

tensor([2., 2., 2.], grad_fn=<MulBackward0>)

Here, the gradient function (from steps 2,3) used is a *"multiply backwards"* function

In [ ]:
# Calculate gradients of t_Y with respect to t_X
t_Y = t_Y.mean()
grad_Y = t_Y.backward() # dt_Y / dt_X

# print gradients
print(t_X.grad)

tensor([1.3333, 1.3333, 1.3333])


If you try and call `.backward()` without `requires_grad=True` (i.e. we have `requires_grad=False`), then there will be an error.