# **I. Tensor Basics**

In [2]:
import torch

- In Pytorch everything is based off of **Tensor Operations**
    - <u>Tensors are similar to Arrays in Numpy</u>
    - Can have different dimensions (1D, 2D, etc.)

In [3]:
# 1D empty tensor creation example
x = torch.empty(1) # 1D Empty Tensor with 1 element
y = torch.empty(3) # 1D Empty Tensor with 3 elements
print(x)
print(y)

tensor([0.])
tensor([-3.7799e+22,  7.3008e-43,  0.0000e+00])


In [4]:
# higher dimension tensors example
x = torch.empty(2,3) # create a 2D Empty Tensor with 2 columns and 3 rows
y = torch.empty(2,5) # create a 2D Empty Tensor with 3 columns and 5 rows
z = torch.empty(1,2,3) # create a 1x2x3 3D Empty Tensor 

print(x)
print(y)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-3.8665e+22,  7.3008e-43,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[[-3.8371e+22,  7.3008e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [5]:
# Random values in a tensor example
t_random = torch.rand(4) # generate a 1D Tensor with 4 elements, each randomly selected
print(t_random)

tensor([0.8917, 0.1327, 0.4954, 0.3832])


In [6]:
# tensors zeros() example (similar to numpy.zeros())
t_zeros = torch.zeros(2,2) # generate a 2D 2x2 Tensor with 0 for all its values
print(t_zeros)

# similar but with ones 
t_ones = torch.ones(3,3) # generate a 2D 3x3 Tensor with all 1s as its elements
print(t_ones)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# changing datatypes of elements in Tensors
t_olddt = torch.ones(3,5) # create 2D 3x5 Tensor of all ones
t_newdt = torch.ones(3,5, dtype=torch.int) # create 2D 3x5 Tensor of all ones where each 1 is now an int

print("old dt type:", t_olddt.dtype)
print("new dt type:", t_newdt.dtype)

old dt type: torch.float32
new dt type: torch.int32


In [ ]:
# get size of tensor
print(t_newdt.size()) # get size of the 3x5 Tensor previously defined

torch.Size([3, 5])


In [ ]:
# create tensor from other data types --> Python List
t_list = torch.tensor([1,1,2,3,5,8]) # create a 1D Tensor of 6 elements from a similar list 
print(t_list)

tensor([1, 1, 2, 3, 5, 8])
