- Pytorch writes fast deep learning code in Python, running on the GPU
- Accesses many pre-built deep learning models
- Provides environment for whole stack of machine learning
    - Preprocessing data
    - Modelling data
    - Deploying model in application/cloud

# **I. Tensor Basics**

In [2]:
import torch

- In Pytorch everything is based off of **Tensor Operations**
    - <u>Tensors are similar to Arrays in Numpy</u>
    - Can have different dimensions (1D, 2D, etc.)
    - **Acts as a way to *numerically encode* our data**

In [3]:
# 1D empty tensor creation example
x = torch.empty(1) # 1D Empty Tensor with 1 element
y = torch.empty(3) # 1D Empty Tensor with 3 elements
print(x)
print(y)

tensor([-2.4191e+24])
tensor([0., 0., 0.])


In [4]:
# higher dimension tensors example
x = torch.empty(2,3) # create a 2D Empty Tensor with 2 columns and 3 rows
y = torch.empty(2,5) # create a 2D Empty Tensor with 3 columns and 5 rows
z = torch.empty(1,2,3) # create a 1x2x3 3D Empty Tensor 

print(x)
print(y)
print(z)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[-2.4746e+24,  1.8721e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[[-2.4557e+24,  1.8721e-42,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])


In [5]:
# Random values in a tensor example
t_random = torch.rand(4) # generate a 1D Tensor with 4 elements, each randomly selected
print(t_random)

tensor([0.4125, 0.8770, 0.7844, 0.0092])


In [6]:
# tensors zeros() example (similar to numpy.zeros())
t_zeros = torch.zeros(2,2) # generate a 2D 2x2 Tensor with 0 for all its values
print(t_zeros)

# similar but with ones 
t_ones = torch.ones(3,3) # generate a 2D 3x3 Tensor with all 1s as its elements
print(t_ones)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# changing datatypes of elements in Tensors
t_olddt = torch.ones(3,5) # create 2D 3x5 Tensor of all ones
t_newdt = torch.ones(3,5, dtype=torch.int) # create 2D 3x5 Tensor of all ones where each 1 is now an int

print("old dt type:", t_olddt.dtype)
print("new dt type:", t_newdt.dtype)

old dt type: torch.float32
new dt type: torch.int32


In [8]:
# get size of tensor
print(t_newdt.size()) # get size of the 3x5 Tensor previously defined

torch.Size([3, 5])


In [9]:
# create tensor from other data types --> Python List
t_list = torch.tensor([1,1,2,3,5,8]) # create a 1D Tensor of 6 elements from a similar list 
print(t_list)

tensor([1, 1, 2, 3, 5, 8])


## Tensor Operations

Adding/Subtracting Tensors is similar to adding/subtracting matrices, they must be the same dimensions to work.

In [15]:
# Adding Tensors
t1 = torch.tensor([[2,2], [1,1]]) # create a 2x2 Tensor of random values
t2 = torch.tensor([[0,3], [3,0]]) # create another 2x2 Tensor of random values
t3 = t1 + t2 

print(t1)
print(t2)
print()
print(t3)

# Alternatively we can use torch.add(t1, t2) to get the same result

tensor([[2, 2],
        [1, 1]])
tensor([[0, 3],
        [3, 0]])

tensor([[2, 5],
        [4, 1]])


In [16]:
# In-Place (modifys a current variable) addition example
t2.add_(t1) # add t1 and t2 and set the value of t2 to be that sum
print(t2)

tensor([[2, 5],
        [4, 1]])


*note that every function in pytorch with **_ will always be an inplace function***

Multiplying Tensors using * or torch.mul() will result in element-wise multiplication (similar to addition)

In [ ]:
# Multiplying Tensors
t4 = t1 * t2
print(t4)

t4_alt = torch.mul(t1,t2)
print(t4_alt)

# inplace is once again denoted by t4.mul_(t1,t2)
# division is t1 / t2 or torch.div(t1,t2)

tensor([[ 4, 10],
        [ 4,  1]])
tensor([[ 4, 10],
        [ 4,  1]])


## Slicing Tensors

In [20]:
t_toslice = torch.rand(3,3) # initialize random 3x3 Tensor
print(t_toslice)

tensor([[0.0023, 0.4944, 0.3564],
        [0.6718, 0.8608, 0.2113],
        [0.6987, 0.7278, 0.1380]])


In [ ]:
# slicing to just get the first row
print(t_toslice[0,:]) # slice, getting just the first row (arg1 = 0) and keeping all the other columns (denote using :)

# slicing to get the 2nd and 3rd columns and the 1st and 2nd rows (OUTER BOUND IS EXCLUSIVE!)
print(t_toslice[0:2, 1:3])

tensor([0.0023, 0.4944, 0.3564])
tensor([[0.4944, 0.3564],
        [0.8608, 0.2113]])


In [ ]:
# .item() gets us the actual value for just one value
print(t_toslice[1,1].item()) # get entry in row 2, col 2

0.8608312606811523


In [26]:
# reshaping tensors (.view())
initial = torch.ones(4,4) # create a 4x4 2D Tensor, we want to reshape this into different dimension (e.g. 4x4 to 16x1)
print(initial)
t_new = initial.view(16) # reshape as a 1x16 1D Tensor
print(t_new)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [ ]:
# tensor to numpy
import numpy as np

t_a = torch.ones(4)
print(t_a)
print(type(t_a))

t_b = t_a.numpy() # convert from tensor to numpy array using numpy()
print(t_b)
print(type(t_b))

tensor([1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1.]
<class 'numpy.ndarray'>


Apparently if the tensor is stored on a CPU instead of a GPU the numpy and tensor share the same memory location, so modifying one will modify the other??

In [32]:
# this does happen in this case
t_a.add_(torch.tensor([1,1,1,1]))
print(t_a)
print(t_b)

tensor([3., 3., 3., 3.])
[3. 3. 3. 3.]


In [ ]:
# numpy to tensor
num_a = np.ones(3) 
num_b = torch.from_numpy(num_a)

print(num_a)
print(type(num_a))
print(num_b)
print(type(num_b))

# modtifying issue still occurs here
# you can add the dtype= parameter to .from_numpy() to change data type as well

[1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [ ]:
# one way to make it write tensors on the gpu is:
if torch.cuda.is_available():
    print("This is writing on the GPU")
    device = torch.device("cuda") 

    # now create tensor like normal but with parameter specifying we wnat to put in on the GPU
    t_t = torch.ones(5, device=device)

    # We can also move a current one to the gpu
    t_t2 = torch.ones(4) # this one creates a tensor but on the cpu like normal
    t_t2 = t_t2.to(device) # MOVES the already-made tensor to the gpu

else:
    print("False")

# Note that numpy will make errors in the inner if because it can only handle cpu tensors
# we can use .to("cpu") to move the tensor back to the cpu

False


*required_grad* is a parameter which tells the machine to calculate the gradients for the specified tensor in optimizing it (which requires gradients). 
- Initially false by default

In [38]:
t_optimized = torch.ones(5, requires_grad=True)
print(t_optimized)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
